import type { NextPage } from 'next';
import { signIn, signOut, useSession } from 'next-auth/react';
import Head from 'next/head';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
  const { data, status } = useSession();
  const entries = trpc.useQuery(['entry.list']);
  console.log(entries);

  if (status === 'unauthenticated') {
    return (
      <>
        <button onClick={() => signIn()}>Sign in</button>
      </>
    );
  }

  if (status === 'loading') {
    return <>Loading...</>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>
          Create <span>T3</span> App
        </h1>

        <div>
          <h3>This stack uses:</h3>
          <ul>
            <li>
              <a href="https://nextjs.org" target="_blank" rel="noreferrer">
                Next.js
              </a>
            </li>
            <li>
              <a href="https://trpc.io" target="_blank" rel="noreferrer">
                tRPC
              </a>
            </li>
            <li>
              <a
                href="https://typescriptlang.org"
                target="_blank"
                rel="noreferrer"
              >
                TypeScript
              </a>
            </li>
          </ul>
          <div>User: {data?.user?.name}</div>
          <div>Email: {data?.user?.email}</div>
          <button onClick={() => signOut()}>Sign out</button>
          <h3>Entries:</h3>
          {entries.data?.entries
            .slice(0)
            .reverse()
            .map((entry) => {
              return (
                <div key={entry.id}>
                  <div>{entry.initialText}</div>
                  <div>{entry.correctedText}</div>
                  <div>{entry.createdAt}</div>
                </div>
              );
            })}

          {/* <div>{data ? <p>{data.greeting}</p> : <p>Loading..</p>}</div> */}
        </div>
      </div>
    </>
  );
};

export default Home;
